spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: test
    password: test
  datasource:
    username: root
    password: 123456
    url: 'jdbc:mysql://192.168.99.100:3306/jemmy_order?zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true'
  redis:
    host: 192.168.99.100
    port: 6379
    password: